### ISSUE TITLE
hugo server

### ISSUE THREAD

**Issue by Qyoom** [commonplaceworld/udacity-hugo-theme#2]
I cloned udacity-hugo-theme and thought I should be able to run it locally from a terminal cmd line with "hugo server". But I get a blank page.

**Comment by ammarasmro** [comment]
I think I know what's wrong, is your themes directory empty?

You might need to clone the theme separately

**Comment by ammarasmro** [comment]
The theme documentation also says that you should run `npm install` within the theme directory

**Comment by ammarasmro** [comment]
FIxed by removing the git submodule with
git rm --cached path_to_submodule
Obtained from https://gist.github.com/myusuf3/7f645819ded92bda6677
