### ISSUE TITLE
Hugo site not deployed

### ISSUE THREAD

**Issue by ammarasmro** [commonplaceworld/udacity-hugo-theme#4]
The commonplaceworld.github.io repo currently only has the CNAME and the README.md

**Comment by ammarasmro** [comment]
@Qyoom 
Inorder to deploy website, according to the documentation of Hugo.

In the directory of the udacity-hugo-theme, run the command
```bash
hugo
```
This should process the website and add the compiled version to the public directory, which is a submodule. 
Now move into that directory and make sure it refers to commonplaceworld.github.io
```bash
cd public
git remote -vl
```
If it is, now commit and push the master branch
```bash
git add .
git commit -m "msg"
git push origin master
```

**Comment by Qyoom** [comment]
Ok, yes. Now hugo built the files into public. But I'm not able to get git to add them!

**Comment by ammarasmro** [comment]
What's the error that you are getting?
Is the remote set properly?

What's the result of running this command?
`git remote -v`

**Comment by Qyoom** [comment]
Ok, was able to add, commit, push from inside the public folder because it's a separate repo. But the hugo site looks whacked. I'm trying to find your note about building sass.

**Comment by ammarasmro** [comment]
I can fix the baseurl and push the change if you like. This is caused by the fact that our baseurl in config.yaml is using http instead of https. Let me know how you want to proceed

**Comment by Qyoom** [comment]
You had it right. Followed your steps and commonplace.world looks as expected. Question: Is it kosher to not have www in the url?

**Comment by Qyoom** [comment]
Thanks!

**Comment by ammarasmro** [comment]
I don't think that it would cause problems to include the www if the domain can accept it but since our website is served as commonplace.world it's better to have the static files served from commonplace.world/css/....
