### ISSUE TITLE
deploy.sh hangs

### ISSUE THREAD

**Issue by Qyoom** [commonplaceworld/udacity-hugo-theme#6]
I'm having trouble using deploy.sh
It's not pushing my changes. I've run "hugo" first.

When I try "git push" in the public dir it hangs.

I have made changes to about/_index.md and about/contact.md and can't push them.

I'm also confused about the message "On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean"

This may have something to do with my ssh key which I may be having trouble with?

![image](https://user-images.githubusercontent.com/1784866/41865792-02d3cc92-7863-11e8-8b53-0897b9a21d1a.png)

**Comment by Qyoom** [comment]
I fixed/resolved this issue by re-cloning the repo and following the setup and deploy scripts. I think I had gotten something out of whack by using git add/commit/push a la carte.

**Comment by ammarasmro** [comment]
Glad that you were able to fix it. I think that we should start working on branches to avoid being behind when we both work at the same time. What do you think?

**Comment by Qyoom** [comment]
Yes, I agree. Just so I remind myself how this should work, let me outline a process—please give me your feedback and suggestions. Let me know if I'm missing anything, etc. We could post such an outline as part of a suggested collaborative project process.

1. First, before doing new work, I create a branch (labeled appropriately for that work), and I do the work and test it on the branch.
2. When I'm ready to merge and deploy, I first do a fetch and pull any new commits by others to the master (to avoid collisions).
3. Then I merge my branch into the master and resolve any issues. Then commit and push.
4. Rinse and repeat.

What about pull requests? Do they have any merit now when there's just the two of us and we use branches? What about later if there gets to be a more participants? Here is a good article I found about project workflow, btw:
http://oss-watch.ac.uk/resources/pullrequest

**Comment by ammarasmro** [comment]
I like this outline. One thing I keep having issue with is that the deploy script doesn't pull the changes for the public repo (commonplaceworld.github.io). Which is creating lots of conflict so instead I'm rerunning the submodule script. I'll test adding it to a test repo then add it here.

Regarding pull requests, I think that we can use branches once we have a stable theme. Then when we want to add a feature, we can open a branch, work on it, then open a pull request to have a more organized and visible workflow. Another workflow could be added for writing posts.

**Comment by Qyoom** [comment]
Actually, I was kind of thinking about how nice it would be to make that script smarter and take care of likely cases as you describe. That would be a big productivity help. Thx, if your able to do it!

**Comment by ammarasmro** [comment]
I added the pull command to the deploy script but I don't have something to test it with. Let me know if it still causes any issues. I'll keep this issue open for a week till we make sure it's not causing any problems.

**Comment by Qyoom** [comment]
Ok, I will deploy a blog post and a jupyter notebook in the next couple of days and see how it goes. **Question**: It sounds like the pull request would become part of the workflow, then, right? I'm good with that. I've always liked the idea that code gets examined and talked about (at least just accepted if it's minor, or discussed otherwise to whatever degree necessary.)

**Comment by ammarasmro** [comment]
Yes I think that is the best way to go. At least we can manage the conflicts that arise from working on the same files at the same time.
