### ISSUE TITLE
Remove redundant BOLD theme link

### ISSUE THREAD

**Issue by Qyoom** [commonplaceworld/udacity-hugo-theme#7]
There are two links to the hugo-smorg theme at the bottom of each page. I'd like to be able to remove the very glaring bold one and leave the less intrusive one that is below it. Can we remove the "An open source theme by Mike Watkins Hugo-smorg" link?

**Comment by ammarasmro** [comment]
Nice observation. What do you think of this solution? @Qyoom 

<img width="1005" alt="screen shot 2018-06-25 at 8 20 52 pm" src="https://user-images.githubusercontent.com/22536934/41885465-59cd08b8-78b5-11e8-9726-9d4b055cb143.png">

**Comment by Qyoom** [comment]
That looks good. Go live with it? Thanks!
